# -*- coding: UTF-8 -*-
####################################################################################################################
# Generated by Warband Module Decompiler
# All rights of the module belong to their respective owners
####################################################################################################################

from header_common import *
from header_parties import *
from ID_troops import *
from ID_factions import *
from ID_party_templates import *
from ID_map_icons import *

####################################################################################################################
#  Each party record contains the following fields:
#  1) Party id: used for referencing parties in other files.
#     The prefix p_ is automatically added before each party id.
#  2) Party name.
#  3) Party flags. See header_parties.py for a list of available flags
#  4) Menu. ID of the menu to use when this party is met. The value 0 uses the default party encounter system.
#  5) Party-template. ID of the party template this party belongs to. Use pt_none as the default value.
#  6) Faction.
#  7) Personality. See header_parties.py for an explanation of personality flags.
#  8) Ai-behavior
#  9) Ai-target party
# 10) Initial coordinates.
# 11) List of stacks. Each stack record is a triple that contains the following fields:
#   11.1) Troop-id. 
#   11.2) Number of troops in this stack. 
#   11.3) Member flags. Use pmf_is_prisoner to note that this member is a prisoner.
# 12) Party direction in degrees [optional]
####################################################################################################################

no_menu = 0
#pf_town = pf_is_static|pf_always_visible|pf_hide_defenders|pf_show_faction
pf_town = pf_is_static|pf_always_visible|pf_show_faction|pf_label_large
pf_castle = pf_is_static|pf_always_visible|pf_show_faction|pf_label_medium
pf_village = pf_is_static|pf_always_visible|pf_hide_defenders|pf_label_small

#sample_party = [(trp_swadian_knight,1,0), (trp_swadian_peasant,10,0), (trp_swadian_crossbowman,1,0), (trp_swadian_man_at_arms, 1, 0), (trp_swadian_footman, 1, 0), (trp_swadian_militia,1,0)]

parties = [
 ("main_party", "Main Party", pf_limit_members, no_menu, pt_none, fac_player_faction, 0, ai_bhvr_hold, 0, (17, 52.5), [(trp_player, 1, 0)]),
 ("temp_party", "temp party", pf_disabled, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),
 ("camp_bandits", "camp bandits", pf_disabled, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (1, 1), [(trp_unarmed_troop, 3, 0)]),
 ("temp_party_2", "temp party 2", pf_disabled, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),
 ("temp_casualties", "casualties", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("temp_casualties_2", "casualties", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("temp_casualties_3", "casualties", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("temp_wounded", "enemies wounded", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("temp_killed", "enemies killed", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("main_party_backup", " ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("encountered_party_backup", " ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("collective_friends_backup", " ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("player_casualties", " ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("enemy_casualties", " ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("ally_casualties", " ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("collective_enemy", "collective enemy", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("collective_ally", "collective ally", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("collective_friends", "collective ally", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("main_party_separated", " ", pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (1, 1), []),
 ("zendar", "Zendar", icon_town|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (16.07, 58.55), []),
 ("town_1", "El Paso", icon_usa_town_a|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (48, -16), [], 130),
 ("town_2", "Bishop's Lodge", icon_usa_town_b|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-17.33, 5.03), [], 120),
 ("town_3", "Cottonwood", icon_usa_town_a|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-13.08, 55.86), [], 80),
 ("town_4", "San Casteabro", icon_mexican_town_a|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (66.92, 9.67), [], 290),
 ("town_5", "El Rio", icon_mexican_town_a|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (29.22, 29.66), []),
 ("town_6", "Buena Fortuna", icon_mexican_town_a|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-72.86, 68.43), [], 155),
 ("town_7", "Kuhtu", icon_teepee_town|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-64.21, -21.46), [], 240),
 ("town_8", "Bikohyooyaa", icon_teepee_town|pf_town, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (17.13, -64.77), [], 175),
 ("town_1b", "El Paso Hotel", icon_usa_town_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (49.45, -14.5), [], 220),
 ("town_2b", "Bishop's Lodge Hotel", icon_usa_town_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-17.13, 7.27), [], 120),
 ("town_3b", "Cottonwood Hotel", icon_usa_town_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-11, 55.75), [], 170),
 ("town_4b", "Hotel San Casteabro", icon_mexican_town_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (64.84, 11.27), [], 290),
 ("town_5b", "Hotel del Rio", icon_mexican_town_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (27.01, 28.34), [], 90),
 ("town_6b", "Hotel Buena Fortuna", icon_mexican_town_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-75.06, 68.88), [], 155),
 ("village_7b", "Shady Valley Hotel", icon_usa_village_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-9.17, 20.9), [], 200),
 ("village_9b", "Hotel Vista del Sol", icon_mexican_village_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (38.09, 34.58), [], 130),
 ("village_17b", "Salvation Hotel", icon_usa_village_hotel|pf_is_static|pf_always_visible|pf_show_faction, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (31.98, 1.79), [], 215),
 ("castle_1", "Camp Luther", icon_fort|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-24.58, -4.66), [], 50),
 ("castle_2", "Fort Helena", icon_fort|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (50.03, -42.55), [], 75),
 ("castle_3", "Fort Miles", icon_fort|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (0, -20), [], 100),
 ("castle_4", "Fort Frederic", icon_fort|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (5.07, 48.86), [], 180),
 ("castle_5", "Fuerte del Sol", icon_castle_d|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (9.84, 85.92), [], 90),
 ("castle_6", "Tupi Sokoobi", icon_fort|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-70.05, 2.97), [], 55),
 ("castle_7", "Fuerte de los Rios", icon_castle_d|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (28.01, 57.02), [], 45),
 ("castle_8", "Fuerte Robusta", icon_castle_d|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-57.18, 80.55), [], 30),
 ("castle_9", "Nchaago Inlwozh", icon_fort|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (34.23, -55.65), [], 100),
 ("castle_10", "Dziilcho", icon_fort|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (4.19, -52.95), [], 110),
 ("castle_11", "Tupi Wunu", icon_fort|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-41, -2.47), [], 75),
 ("castle_12", "Fuerte Impenetrable", icon_castle_d|pf_castle, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (50, 35.08), [], 95),
 ("village_1", "Desperation", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-29.4, 40.54), [], 100),
 ("village_2", "Nadahstan", icon_teepee|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (11.79, -51.37), [], 110),
 ("village_3", "Pueblo del Cactus", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (66.5, 27.76), [], 120),
 ("village_4", "Santo Poco", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (18.81, 87.4), [], 130),
 ("village_5", "Robertston", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-15.4, 82.13), [], 170),
 ("village_6", "Rock Ridge", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-12.12, -11), [], 100),
 ("village_7", "Shady Valley", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-8.79, 19.62), [], 110),
 ("village_8", "Aguas Ponzonosas", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-86.16, 60.86), [], 120),
 ("village_9", "Vista del Sol", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (39.38, 32.97), [], 130),
 ("village_10", "La Cumbre", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-60.64, 94.99), [], 170),
 ("village_11", "Nadawisgah", icon_teepee|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (32.9, -74), [], 100),
 ("village_12", "Ata Kahni", icon_teepee|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-54.99, -10.26), [], 110),
 ("village_13", "Tumblewood", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (26.85, -15.6), [], 120),
 ("village_14", "Dunas Altas", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (40, 52), [], 130),
 ("village_15", "Arenas Rojas", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-78.31, 83.09), [], 170),
 ("village_16", "Tres Piedras", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (73.5, -15.97), [], 170),
 ("village_17", "Salvation", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (32.92, 0.56), [], 125),
 ("village_18", "Riverton", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-37.57, 56.57), [], 170),
 ("village_19", "Benton's Mill", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (63.24, -39.92), [], 30),
 ("village_20", "Puerta del Desierto", icon_mexican_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (83.54, 11.36), [], 170),
 ("village_21", "Tannersville", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-2.52, 3.91), [], 100),
 ("village_22", "Eureka", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (0.16, 66.25), [], 110),
 ("village_23", "Taibo Suku'i", icon_teepee|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-54.2, -29.61), [], 120),
 ("village_24", "Nuetutsi", icon_teepee|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-80.98, -13.01), [], 130),
 ("village_25", "Deeschii'", icon_teepee|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (6.65, -72.46), [], 170),
 ("village_26", "Jansen-Williamson Ranch", icon_usa_village|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-19.9, 58), [], 170),
 ("bank_1", "El Paso Bank", icon_usa_town_bank|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (47.14, -17.4), [], 40),
 ("bank_2", "El Rio Bank", icon_mexican_town_bank|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (29.35, 32.46), []),
 ("salt_mine", "Salt Mine", icon_village_a|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (14.2, -31), []),
 ("four_ways_inn", "Four Ways Inn", icon_village_a|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (4.8, -39.6), []),
 ("test_scene", "test scene", icon_village_a|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (10.8, -19.6), []),
 ("battlefields", "battlefields", icon_village_a|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (10.8, -16.6), []),
 ("dhorak_keep", "Dhorak Keep", icon_town|pf_village|pf_disabled|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-50, -58), []),
 ("mine_1", "Mine", icon_mine_small|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-43.42, 13.25), [], 350),
 ("graveyard_1", "Graveyard", icon_graveyard|pf_is_static|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (57, -3), [], 350),
 ("telegraph_1", " ", icon_telegraph|pf_is_static|pf_always_visible|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (5, -17), [], 350),
 ("old_cabin", "Old Cabin", icon_cabin|pf_village, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-56, -82), [], 350),
 ("tull", "Tull", icon_usa_town_a|pf_is_static|pf_hide_defenders, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-12.12, -42.55), [], 350),
 ("target", "Mission Target", icon_target|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-24.2, -75), []),
 ("bl_station", "Station", icon_cabin|pf_village|pf_no_label, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-18.13, 8.27), [], 350),
 ("bounty_hunters_honorable_ambush", "Ambush Location", icon_ambush|pf_disabled|pf_no_label, no_menu, pt_none, fac_bounty_hunters, 0, ai_bhvr_hold, 0, (-18.13, 6.27), [], 350),
 ("bounty_hunters_dishonorable_ambush", "Ambush Location", icon_ambush|pf_disabled|pf_no_label, no_menu, pt_none, fac_bounty_hunters, 0, ai_bhvr_hold, 0, (-18.13, 7.27), [], 350),
 ("training_ground", "Training Ground", icon_training_ground|pf_village|pf_disabled, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (3, -7), []),
 ("training_ground_1", "Training Field", icon_training_ground|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (46.89, 60.01), [], 100),
 ("training_ground_2", "Training Field", icon_training_ground|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-38, 81.7), [], 100),
 ("training_ground_3", "Training Field", icon_training_ground|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (88.9, 17.56), [], 100),
 ("training_ground_4", "Training Field", icon_training_ground|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (9.5, -80.5), [], 100),
 ("training_ground_5", "Training Field", icon_training_ground|pf_village|pf_label_medium, no_menu, pt_none, fac_neutral, 0, ai_bhvr_hold, 0, (-34.75, -30.3), [], 100),
 ("forest_bandit_spawn_point_1", "forest bandit sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (39.21, 60.17), []),
 ("forest_bandit_spawn_point_2", "forest bandit sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-8.15, -34.27), []),
 ("mountain_bandit_spawn_point_1", "mountain bandit sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-11, 30.92), []),
 ("mountain_bandit_spawn_point_2", "mountain bandit sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-47.37, 16.31), []),
 ("indian_raider_spawn_point_1", "indian raider sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (48.83, -60.06), []),
 ("indian_raider_spawn_point_2", "indian raider sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-26.67, -39.94), []),
 ("indian_raider_spawn_point_3", "indian raider sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-83, 28), []),
 ("scalphunter_spawn_point_1", "scalphunter sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (63.61, -50.73), []),
 ("scalphunter_spawn_point_2", "scalphunter sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (10.29, 30.52), []),
 ("scalphunter_spawn_point_3", "scalphunter sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-55.73, 35.84), []),
 ("trapper_spawn_point_1", "trapper sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-38.77, -56.63), []),
 ("trapper_spawn_point_2", "trapper sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (61.69, -47.32), []),
 ("trapper_spawn_point_3", "trapper sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-32.6, 73.45), []),
 ("miner_spawn_point_1", "miner sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-42.14, 13.09), []),
 ("miner_spawn_point_2", "miner sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-31.05, 8.6), []),
 ("miner_spawn_point_3", "miner sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (34.89, -21.35), []),
 ("homesteader_spawn_point_1", "homesteader sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-28, -21.98), []),
 ("homesteader_spawn_point_2", "homesteader sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-104.95, 37.65), []),
 ("homesteader_spawn_point_3", "homesteader sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (40.36, 16.36), []),
 ("imperialist_spawn_point_1", "imperialist sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (83.3, -13.19), []),
 ("imperialist_spawn_point_2", "imperialist sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (55.61, 46.95), []),
 ("imperialist_spawn_point_3", "imperialist sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (29.39, 75.77), []),
 ("confederate_renegade_spawn_point_1", "confederate renegade sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-83.62, 22.02), []),
 ("confederate_renegade_spawn_point_2", "confederate renegade sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-14.33, 23.94), []),
 ("confederate_renegade_spawn_point_3", "confederate renegade sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (61.67, -53.14), []),
 ("deer_spawn_point_1", "deer sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-35.55, -19.3), []),
 ("deer_spawn_point_2", "deer sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (61.21, -46.92), []),
 ("deer_spawn_point_3", "deer sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (44.95, 59.81), []),
 ("deer_spawn_point_4", "deer sp 4", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-18.28, -2.57), []),
 ("deer_spawn_point_5", "deer sp 5", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-64.01, -74.55), []),
 ("deer_spawn_point_6", "deer sp 6", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-56, -82), []),
 ("buffalo_spawn_point_1", "buffalo sp 1", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (29.92, -84.57), []),
 ("buffalo_spawn_point_2", "buffalo sp 2", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-68.99, -10.54), []),
 ("buffalo_spawn_point_3", "buffalo sp 3", pf_disabled|pf_is_static, no_menu, pt_none, fac_outlaws, 0, ai_bhvr_hold, 0, (-98.89, 36.91), []),
 ("spawn_points_end", "last spawn point", pf_disabled|pf_is_static, no_menu, pt_none, fac_commoners, 0, ai_bhvr_hold, 0, (0, 0), []),
]