# -*- coding: UTF-8 -*-
####################################################################################################################
# Generated by Warband Module Decompiler
# All rights of the module belong to their respective owners
####################################################################################################################

from header_music import *
####################################################################################################################
#  Each track record contains the following fields:
#  1) Track id: used for referencing tracks.
#  2) Track file: filename of the track
#  3) Track flags. See header_music.py for a list of available flags
#  4) Continue Track flags: Shows in which situations or cultures the track can continue playing. See header_music.py for a list of available flags
####################################################################################################################

# WARNING: You MUST add mtf_module_track flag to the flags of the tracks located under module directory

tracks = [
  ("cant_find_this", "cant_find_this.ogg", 0, 0),
  ("wind", "wind.mp3", mtf_start_immediately|mtf_module_track, mtf_sit_town|mtf_sit_travel),
  ("capture", "capture.ogg", mtf_persist_until_finished, 0),
  ("And_Awaken", "And_Awaken.mp3", mtf_persist_until_finished, 0),
  ("Ghost_Processional", "Ghost_Processional.mp3", mtf_start_immediately|mtf_module_track, 0),
  ("As_the_Dust_Settles", "As_the_Dust_Settles.mp3", mtf_start_immediately|mtf_sit_victorious|mtf_module_track, 0),
  ("Western_Lead_Title", "Western_Lead_Title.mp3", mtf_start_immediately|mtf_sit_main_title|mtf_module_track, mtf_sit_travel),
  ("Shamanistic", "Shamanistic.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Night_Of_The_Owl", "Night_Of_The_Owl.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Thunderhead", "Thunderhead.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Firesong", "Firesong.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Dusty_Battle", "Dusty_Battle.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Hunted_by_Indians", "Hunted_by_Indians.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Western_Lead_Title", "Western_Lead_Title.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Fire_Dance", "Fire_Dance.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Back_in_the_Saddle", "Back_in_the_Saddle.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Cminor", "Cminor.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("gunslingers_requiem_2", "gunslingers_requiem_2.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Nocturnal_Deathwish", "Nocturnal_Deathwish.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Redemption", "Redemption.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Land_Of_The_Setting_Sun", "Land_Of_The_Setting_Sun.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("wind", "wind.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Dangerous", "Dangerous.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Evil_March", "Evil_March.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Exciting_Trailer", "Exciting_Trailer.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Failing_Defense", "Failing_Defense.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Sidewinder", "Sidewinder.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Apache_Sunset", "Apache_Sunset.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_fight|mtf_sit_siege|mtf_module_track, 0),
  ("Western_Goldrush_Orchestral", "Western_Goldrush_Orchestral.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("happyfarmer", "happyfarmer.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("opus18ebmaj", "opus18ebmaj.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Lonesome_Road_Blues", "Lonesome_Road_Blues.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("1866_Rag", "1866_Rag.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Turkey_In_The_Straw", "Turkey_In_The_Straw.ogg", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Fig_Leaf_Rag", "Fig_Leaf_Rag.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Gold_Rush", "Gold_Rush.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Merry_Go_Slower", "Merry_Go_Slower.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Mano_a_Mano", "Mano-a-Mano.mp3", mtf_culture_2|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Laid_Back_Guitars", "Laid_Back_Guitars.mp3", mtf_culture_2|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Western_Draw", "Western_Draw.mp3", mtf_culture_2|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Okefenagua", "Okefenagua.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Flaming_Gorge", "Flaming_Gorge.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_town|mtf_module_track, 0),
  ("Western_Up_Tempo_Walk", "Western_Up_Tempo_Walk.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("Alone_On_The_Plains", "Alone_On_The_Plains.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("As_the_Dust_Settles", "As_the_Dust_Settles.mp3", mtf_culture_2|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("Laid_Back_Guitars", "Laid_Back_Guitars.mp3", mtf_culture_2|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("Western_Draw", "Western_Draw.mp3", mtf_culture_2|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("Firesong", "Firesong.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("Thunderhead", "Thunderhead.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("Ennino_Morricone_ish", "Ennino_Morricone-ish.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("Land_Of_The_Setting_Sun", "Land_Of_The_Setting_Sun.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("wind", "wind.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_travel|mtf_module_track, 0),
  ("yellowrose", "yellowrose.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_victorious|mtf_module_track, mtf_sit_fight),
  ("Western_Goldrush_Orchestral", "Western_Goldrush_Orchestral.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_victorious|mtf_module_track, mtf_sit_fight),
  ("Dead_Mans_Moon", "Dead_Mans_Moon.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_victorious|mtf_module_track, mtf_sit_fight),
  ("Smoking_Gun", "Smoking_Gun.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town_infiltrate|mtf_module_track, 0),
  ("Western_Streets", "Western_Streets.mp3", mtf_culture_1|mtf_start_immediately|mtf_sit_town_infiltrate|mtf_module_track, 0),
  ("Two_Heroes", "Two_Heroes.mp3", mtf_culture_2|mtf_start_immediately|mtf_sit_town_infiltrate|mtf_module_track, 0),
  ("Shamanistic", "Shamanistic.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_town_infiltrate|mtf_module_track, 0),
  ("Night_Of_The_Owl", "Night_Of_The_Owl.mp3", mtf_culture_3|mtf_culture_4|mtf_start_immediately|mtf_sit_town_infiltrate|mtf_module_track, 0),
  ("Evil_March", "Evil_March.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_ambushed|mtf_module_track, 0),
  ("Hunted_by_Indians", "Hunted_by_Indians.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_ambushed|mtf_module_track, 0),
  ("Dangerous", "Dangerous.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_ambushed|mtf_module_track, 0),
  ("Exciting_Trailer", "Exciting_Trailer.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_ambushed|mtf_module_track, 0),
  ("Failing_Defense", "Failing_Defense.mp3", mtf_culture_all|mtf_start_immediately|mtf_sit_ambushed|mtf_module_track, 0),
  ("Hero_Theme", "Hero_Theme.mp3", mtf_culture_all|mtf_persist_until_finished|mtf_sit_killed, 0),
  ("defeated_by_neutral_3", "defeated_by_neutral_3.ogg", mtf_culture_all|mtf_persist_until_finished|mtf_sit_killed, 0),
]