# -*- coding: UTF-8 -*-
####################################################################################################################
# Generated by Warband Module Decompiler
# All rights of the module belong to their respective owners
####################################################################################################################

from header_common import *
from header_parties import *
from ID_troops import *
from ID_factions import *
from ID_map_icons import *

pmf_is_prisoner = 0x0001

####################################################################################################################
#  Each party template record contains the following fields:
#  1) Party-template id: used for referencing party-templates in other files.
#     The prefix pt_ is automatically added before each party-template id.
#  2) Party-template name.
#  3) Party flags. See header_parties.py for a list of available flags
#  4) Menu. ID of the menu to use when this party is met. The value 0 uses the default party encounter system.
#  5) Faction
#  6) Personality. See header_parties.py for an explanation of personality flags.
#  7) List of stacks. Each stack record is a tuple that contains the following fields:
#    7.1) Troop-id. 
#    7.2) Minimum number of troops in the stack. 
#    7.3) Maximum number of troops in the stack. 
#    7.4) Member flags(optional). Use pmf_is_prisoner to note that this member is a prisoner.
#     Note: There can be at most 6 stacks.
####################################################################################################################


party_templates = [
  ("none", "none", icon_outlaw_soldier, 0, fac_commoners, merchant_personality, []),
  ("rescued_prisoners", "Rescued_Prisoners", icon_outlaw_soldier, 0, fac_commoners, merchant_personality, []),
  ("enemy", "Enemy", icon_outlaw_soldier, 0, fac_undeads, merchant_personality, []),
  ("hero_party", "Hero_Party", icon_outlaw_soldier, 0, fac_commoners, merchant_personality, []),
  ("village_defenders", "Village_Defenders", icon_peasant, 0, fac_commoners, merchant_personality, [(trp_settler_1, 10, 20),(trp_settler_woman, 0, 4)]),
  ("apache_defenders", "Village_Defenders", icon_peasant, 0, fac_commoners, merchant_personality, [(trp_apache_rabbit_hunter, 10, 25)]),
  ("comanche_defenders", "Village_Defenders", icon_peasant, 0, fac_commoners, merchant_personality, [(trp_comanche_buffalo_hunter, 10, 20)]),
  ("cattle_herd", "Cattle_Herd", icon_cattle|carries_goods(10), 0, fac_neutral, merchant_personality, [(trp_cattle, 80, 120)]),
  ("horses_herd", "Horses_Herd", icon_horses|carries_goods(1), 0, fac_neutral, merchant_personality, [(trp_horses, 50, 80)]),
  ("looters", "Looters", icon_axeman, 0, fac_outlaws, bandit_personality, [(trp_looter_1, 3, 11)]),
  ("forest_bandits", "Plains_Bandits", icon_axeman|carries_goods(2), 0, fac_outlaws, bandit_personality, [(trp_forest_bandit, 5, 52)]),
  ("mountain_bandits", "Canyon_Bandits", icon_outlaw_soldier|carries_goods(2), 0, fac_outlaws, bandit_personality, [(trp_mountain_bandit, 5, 25)]),
  ("outlaws_american", "Outlaws", icon_axeman, 0, fac_outlaws, bandit_personality, [(trp_thief, 6, 16)]),
  ("outlaws_mexican", "Outlaws", icon_axeman, 0, fac_outlaws, bandit_personality, [(trp_marauder, 6, 16)]),
  ("trappers", "Trappers", icon_axeman|carries_goods(7), 0, fac_commoners, merchant_personality, [(trp_trapper_1, 2, 12)]),
  ("miners", "Miners", icon_axeman|carries_goods(7), 0, fac_commoners, merchant_personality, [(trp_miner_1, 4, 20)]),
  ("homesteaders", "Homesteaders", icon_peasant|carries_goods(7), 0, fac_commoners, merchant_personality, [(trp_settler_1, 6, 12),(trp_settler_woman, 1, 3)]),
  ("manhunters", "Vigilantes", icon_lawman_soldier, 0, fac_commoners, soldier_personality, [(trp_manhunter, 3, 10),(trp_posseman, 3, 10),(trp_county_militia, 3, 11),(trp_state_militia, 2, 4)]),
  ("imperialists", "Imperialists", icon_bandit_soldier|carries_goods(2), 0, fac_imperialists, bandit_personality, [(trp_imperial_rural, 8, 12),(trp_imperial_cazadore, 6, 10),(trp_imperial_contra_guerilla, 2, 4)]),
  ("scalphunters", "Scalphunters", icon_axeman|carries_goods(2), 0, fac_scalphunters, bandit_personality, [(trp_cut_throat, 4, 7),(trp_stagecoach_robber, 2, 4),(trp_burglar, 2, 4)]),
  ("indian_raiders", "Indian_Raiders", icon_comanche_soldier|carries_goods(2), 0, fac_indian_raiders, bandit_personality, [(trp_indian_raider_1, 5, 15)]),
  ("confederate_renegades", "Confederate_Renegades", icon_outlaw_soldier|carries_goods(2), 0, fac_confederate_renegades, bandit_personality, [(trp_former_csa_volunteer, 4, 8),(trp_former_csa_regular, 4, 8),(trp_former_csa_sergeant, 3, 6),(trp_former_csa_scout, 3, 6)]),
  ("deserters", "Deserters", icon_outlaw_soldier|carries_goods(3), 0, fac_deserters, bandit_personality, []),
  ("merchant_caravan", "Stagecoach", icon_stagecoach|carries_goods(5)|pf_auto_remove_in_town|pf_quest_party, 0, fac_commoners, escorted_merchant_personality, [(trp_local_militia, 7, 13)]),
  ("troublesome_bandits", "Troublesome_Bandits", icon_axeman|carries_goods(9)|pf_quest_party, 0, fac_outlaws, bandit_personality, [(trp_looter_2, 14, 55)]),
  ("bandits_awaiting_ransom", "Comanches_Awaiting_Ransom", icon_comanche_soldier|carries_goods(9)|pf_auto_remove_in_town|pf_quest_party, 0, fac_neutral, bandit_personality, [(trp_comanche_horse_archer, 7, 14),(trp_comanche_raider, 7, 14),(trp_kidnapped_girl, 1, 1, pmf_is_prisoner)]),
  ("kidnapped_girl", "Kidnapped_Girl", icon_woman|pf_quest_party, 0, fac_neutral, merchant_personality, [(trp_kidnapped_girl, 1, 1)]),
  ("american_chain_gang", "Chain_Gang", icon_lawman_soldier|carries_goods(3), 0, fac_kingdom_1, escorted_merchant_personality, [(trp_county_militia, 5, 20),(trp_state_militia, 1, 4),(trp_deputy_sheriff, 0, 1),(trp_thief, 10, 20, pmf_is_prisoner),(trp_horse_thief, 1, 10, pmf_is_prisoner),(trp_burglar, 0, 5, pmf_is_prisoner)]),
  ("mexican_chain_gang", "Chain_Gang", icon_mexico_soldier|carries_goods(3), 0, fac_kingdom_2, escorted_merchant_personality, [(trp_soldado, 5, 20),(trp_cabo, 1, 4),(trp_carabinero, 0, 1),(trp_marauder, 10, 20, pmf_is_prisoner),(trp_guacho, 1, 10, pmf_is_prisoner),(trp_cut_throat, 0, 5, pmf_is_prisoner)]),
  ("village_farmers", "Settlers", icon_peasant|carries_goods(8), 0, fac_commoners, merchant_personality, [(trp_settler_1, 10, 19),(trp_settler_woman, 2, 6)]),
  ("village_caravan", "Settlers_Caravan", icon_wagon|carries_goods(10)|pf_auto_remove_in_town|pf_quest_party, 0, fac_commoners, escorted_merchant_personality, [(trp_settler_1, 8, 11),(trp_settler_woman, 1, 4)]),
  ("spy_partners", "Unremarkable_Travellers", icon_outlaw_soldier|carries_goods(3)|pf_default_behavior|pf_quest_party, 0, fac_neutral, merchant_personality, [(trp_spy_partner, 1, 1)]),
  ("runaway_serfs", "Runaway_Settlers", icon_peasant|carries_goods(8)|pf_default_behavior|pf_quest_party, 0, fac_neutral, merchant_personality, [(trp_settler_1, 6, 7),(trp_settler_woman, 3, 3)]),
  ("spy", "Ordinary_Traveller", icon_outlaw_soldier|carries_goods(3)|pf_default_behavior|pf_quest_party, 0, fac_neutral, merchant_personality, [(trp_spy, 1, 1)]),
  ("sacrificed_messenger", "Sacrificed_Messenger", icon_outlaw_soldier|carries_goods(3)|pf_default_behavior|pf_quest_party, 0, fac_neutral, merchant_personality, []),
  ("bounty_hunters_honorable", "Honorable_Bounty_Hunters", icon_bounty_hunter, 0, fac_bounty_hunters, courage_9|aggressiveness_8, [(trp_bounty_hunter, 1, 1)]),
  ("bounty_hunters_dishonorable", "Dishonorable_Bounty_Hunters", icon_bounty_hunter, 0, fac_bounty_hunters, courage_9|aggressiveness_8, [(trp_bounty_hunter, 1, 1)]),
  ("forager_party", "Foraging_Party", icon_outlaw_soldier|carries_goods(5)|pf_show_faction, 0, fac_commoners, merchant_personality, []),
  ("scout_party", "Scouts", icon_outlaw_soldier|carries_goods(1)|pf_show_faction, 0, fac_commoners, bandit_personality, []),
  ("patrol_party", "Patrol", icon_outlaw_soldier|carries_goods(2)|pf_show_faction, 0, fac_commoners, soldier_personality, []),
  ("messenger_party", "Messenger", icon_outlaw_soldier|pf_show_faction, 0, fac_commoners, merchant_personality, []),
  ("raider_party", "Raiders", icon_outlaw_soldier|carries_goods(16)|pf_quest_party, 0, fac_commoners, bandit_personality, []),
  ("raider_captives", "Raider_Captives", 0, 0, fac_commoners, 0, [(trp_settler_woman, 6, 30, pmf_is_prisoner)]),
  ("kingdom_caravan_party", "Carriage", icon_wagon|carries_goods(25)|pf_show_faction, 0, fac_commoners, merchant_personality, []),
  ("stagecoach", "Stagecoach", icon_stagecoach|carries_goods(10), 0, fac_commoners, merchant_personality, [(trp_settler_1, 1, 5),(trp_settler_woman, 1, 3),(trp_county_militia, 6, 14),(trp_state_militia, 1, 4),(trp_pinkerton_agent, 1, 2)]),
  ("bank_defenders", "Deputies", icon_player_horseman, 0, fac_commoners, merchant_personality, [(trp_county_militia, 11, 22),(trp_state_militia, 2, 4),(trp_deputy_sheriff, 2, 4),(trp_ranger, 2, 4)]),
  ("deer_herd", "Deer_Herd", icon_deer|carries_goods(10), 0, fac_wild_animals, merchant_personality, [(trp_deer, 8, 15)]),
  ("buffalo_herd", "Buffalo_Herd", icon_buffalo|carries_goods(20), 0, fac_wild_animals, merchant_personality, [(trp_buffalo, 9, 18)]),
  ("prisoner_train_party", "Prisoner_Train", icon_outlaw_soldier|carries_goods(5)|pf_show_faction, 0, fac_commoners, merchant_personality, []),
  ("default_prisoners", "Default_Prisoners", 0, 0, fac_commoners, 0, [(trp_looter_2, 5, 10, pmf_is_prisoner)]),
  ("center_reinforcements", "Reinforcements", icon_axeman|carries_goods(16), 0, fac_commoners, soldier_personality, [(trp_local_militia, 5, 30),(trp_deputy_sheriff, 4, 20)]),
  ("kingdom_hero_party", "War_Party", icon_outlaw_soldier|pf_default_behavior|pf_show_faction, 0, fac_commoners, soldier_personality, []),
  ("kingdom_1_reinforcements_a", "kingdom_2_reinforcements_a", 0, 0, fac_commoners, 0, [(trp_recruit, 6, 18),(trp_infantry_recruit, 2, 7),(trp_cavalry_recruit, 2, 7),(trp_volunteer, 1, 2),(trp_regular, 1, 3)]),
  ("kingdom_1_reinforcements_b", "kingdom_2_reinforcements_b", 0, 0, fac_commoners, 0, [(trp_light_scout, 1, 2),(trp_dragoon, 1, 3),(trp_veteran_volunteer, 3, 9),(trp_veteran_regular, 3, 9),(trp_light_dragoon, 4, 15),(trp_veteran_cavalry, 3, 10)]),
  ("kingdom_1_reinforcements_c", "kingdom_2_reinforcements_c", 0, 0, fac_commoners, 0, [(trp_zouhave, 4, 6),(trp_infantry_sergeant, 2, 7),(trp_cavalry_officer, 2, 7),(trp_elite_cavalry, 3, 10)]),
  ("kingdom_1_reinforcements_d", "kingdom_2_reinforcements_d", 0, 0, fac_commoners, 0, [(trp_dynamite_thrower, 1, 1)]),
  ("kingdom_2_reinforcements_a", "kingdom_4_reinforcements_a", 0, 0, fac_commoners, 0, [(trp_recluta, 8, 14),(trp_soldado, 4, 12),(trp_dragon, 1, 3)]),
  ("kingdom_2_reinforcements_b", "kingdom_4_reinforcements_b", 0, 0, fac_commoners, 0, [(trp_cabo, 4, 10),(trp_husar, 6, 12),(trp_sargento, 1, 3),(trp_carabinero, 1, 3),(trp_lancero_ligero, 1, 2),(trp_oficial_de_los_dragones, 1, 3)]),
  ("kingdom_2_reinforcements_c", "kingdom_4_reinforcements_c", 0, 0, fac_commoners, 0, [(trp_supremos_poderes_riflelero, 3, 6),(trp_lancero_pesado, 3, 6),(trp_supremos_poderes_caballero, 3, 6)]),
  ("kingdom_2_reinforcements_d", "kingdom_4_reinforcements_d", 0, 0, fac_commoners, 0, [(trp_dynamite_thrower, 1, 3)]),
  ("kingdom_3_reinforcements_a", "kingdom_5_reinforcements_a", 0, 0, fac_commoners, 0, [(trp_apache_rabbit_hunter, 2, 6),(trp_apache_scout, 4, 7),(trp_apache_raider, 4, 7)]),
  ("kingdom_3_reinforcements_b", "kingdom_5_reinforcements_b", 0, 0, fac_commoners, 0, [(trp_apache_brave, 4, 7),(trp_apache_thunder_brave, 2, 6),(trp_apache_mounted_brave, 4, 7),(trp_apache_mounted_thunder_brave, 3, 6),(trp_apache_warrior, 4, 7),(trp_apache_thunder_warrior, 2, 6)]),
  ("kingdom_3_reinforcements_c", "kingdom_5_reinforcements_c", 0, 0, fac_commoners, 0, [(trp_apache_sun_dance_spirit, 3, 6),(trp_apache_thunder_spirit, 2, 6),(trp_apache_mounted_warrior, 4, 7),(trp_apache_mounted_thunder_warrior, 4, 7)]),
  ("kingdom_3_reinforcements_d", "kingdom_2_reinforcements_d", 0, 0, fac_commoners, 0, [(trp_dynamite_thrower, 0, 0)]),
  ("kingdom_4_reinforcements_a", "kingdom_3_reinforcements_a", 0, 0, fac_commoners, 0, [(trp_comanche_buffalo_hunter, 2, 6),(trp_comanche_vision_seeker, 2, 6),(trp_comanche_raider, 4, 7),(trp_comanche_medicine_man, 2, 4)]),
  ("kingdom_4_reinforcements_b", "kingdom_3_reinforcements_b", 0, 0, fac_commoners, 0, [(trp_comanche_horse_archer, 4, 7),(trp_comanche_horse_gunner, 4, 7),(trp_comanche_shaman, 2, 6),(trp_comanche_wind_rider, 4, 7)]),
  ("kingdom_4_reinforcements_c", "kingdom_3_reinforcements_c", 0, 0, fac_commoners, 0, [(trp_comanche_warrior_legend, 1, 3),(trp_comanche_fire_rider, 2, 3),(trp_comanche_war_chief, 1, 2)]),
  ("kingdom_4_reinforcements_d", "kingdom_3_reinforcements_d", 0, 0, fac_commoners, 0, [(trp_dynamite_thrower, 0, 0)]),
  ("kingdom_5_reinforcements_a", "kingdom_4_reinforcements_a", 0, 0, fac_commoners, 0, [(trp_vagabond, 9, 16),(trp_marauder, 2, 7),(trp_guacho, 2, 7)]),
  ("kingdom_5_reinforcements_b", "kingdom_4_reinforcements_b", 0, 0, fac_commoners, 0, [(trp_cut_throat, 3, 6),(trp_rustler, 3, 6),(trp_pistolero, 3, 6),(trp_bandito, 3, 6)]),
  ("kingdom_5_reinforcements_c", "kingdom_4_reinforcements_c", 0, 0, fac_commoners, 0, [(trp_assassin, 3, 6),(trp_desperado, 3, 6)]),
  ("kingdom_5_reinforcements_d", "kingdom_4_reinforcements_d", 0, 0, fac_commoners, 0, [(trp_dynamite_thrower, 1, 1)]),
  ("kingdom_6_reinforcements_a", "kingdom_4_reinforcements_a", 0, 0, fac_commoners, 0, [(trp_local_militia, 7, 14),(trp_county_militia, 2, 4),(trp_posseman, 2, 4)]),
  ("kingdom_6_reinforcements_b", "kingdom_4_reinforcements_b", 0, 0, fac_commoners, 0, [(trp_state_militia, 3, 6),(trp_deputy_sheriff, 3, 6),(trp_deputy_marshal, 3, 6)]),
  ("kingdom_6_reinforcements_c", "kingdom_4_reinforcements_c", 0, 0, fac_commoners, 0, [(trp_pinkerton_agent, 2, 4),(trp_ranger, 2, 4)]),
  ("kingdom_6_reinforcements_d", "kingdom_4_reinforcements_d", 0, 0, fac_commoners, 0, [(trp_dynamite_thrower, 1, 1)]),
  ("kingdom_7_reinforcements_a", "kingdom_4_reinforcements_a", 0, 0, fac_commoners, 0, [(trp_gambler, 3, 7),(trp_thief, 3, 7),(trp_horse_thief, 2, 6)]),
  ("kingdom_7_reinforcements_b", "kingdom_4_reinforcements_b", 0, 0, fac_commoners, 0, [(trp_burglar, 2, 4),(trp_stagecoach_robber, 2, 4),(trp_thug, 2, 4),(trp_train_robber, 2, 4)]),
  ("kingdom_7_reinforcements_c", "kingdom_4_reinforcements_c", 0, 0, fac_commoners, 0, [(trp_gunslinger, 2, 4),(trp_bank_robber, 2, 4)]),
  ("kingdom_7_reinforcements_d", "kingdom_4_reinforcements_d", 0, 0, fac_commoners, 0, [(trp_dynamite_thrower, 1, 1)]),
]