# -*- coding: UTF-8 -*-
####################################################################################################################
# Generated by Warband Module Decompiler
# All rights of the module belong to their respective owners
####################################################################################################################

from header_factions import *

####################################################################################################################
#  Each faction record contains the following fields:
#  1) Faction id: used for referencing factions in other files.
#     The prefix fac_ is automatically added before each faction id.
#  2) Faction name.
#  3) Faction flags. See header_factions.py for a list of available flags
#  4) Faction coherence. Relation between members of this faction.
#  5) Relations. This is a list of relation records.
#     Each relation record is a tuple that contains the following fields:
#    5.1) Faction. Which other faction this relation is referring to
#    5.2) Value: Relation value between the two factions.
#         Values range between -1 and 1.
#  6) Ranks
#  7) Faction color (default is gray)
####################################################################################################################

default_kingdom_relations = [("outlaws",-0.05),("peasant_rebels", -0.1),("deserters", -0.05),("mountain_bandits", -0.02),("forest_bandits", -0.02)]
factions = [
  ("no_faction", "No_Faction", 0, 0.0, [("no_faction", 0.9)], []),
  ("commoners", "Commoners", 0, 0.0, [("commoners", 0.1),("outlaws", -0.6),("player_faction", 0.1),("scalphunters", -0.5),("indian_raiders", -0.5),("undeads", -0.7),("bounty_hunters", 1)], []),
  ("outlaws", "Outlaws", max_player_rating(-30), 0.0, [("commoners", -0.6),("outlaws", 0.5),("deserters", -0.05),("player_faction", -0.05),("player_supporters_faction", -0.05),("kingdom_1", -0.05),("kingdom_2", -0.05),("kingdom_3", -0.05),("kingdom_4", -0.05),("scalphunters", -0.5),("indian_raiders", -0.5),("bounty_hunters", 1)], [], 0xFF0000),
  ("deserters", "Deserters", 0, 0.0, [("outlaws", -0.05),("deserters", -0.05),("player_faction", -0.02),("player_supporters_faction", -0.02),("kingdom_1", -0.02),("kingdom_2", -0.02),("kingdom_3", -0.02),("kingdom_4", -0.02),("confederate_renegades", -0.1),("imperialists", -0.1),("scalphunters", -0.1),("indian_raiders", -0.1),("bounty_hunters", 1)], [], 0xFFAAFF),
  ("special_end", "special_end", 0, 0.0, [], []),
  ("neutral", "Neutral", 0, 0.0, [("neutral", 0.1)], [], 0xFFFFFF),
  ("culture_1", "USA", 0, 0.0, [("culture_1", 0.9)], []),
  ("culture_2", "Mexico", 0, 0.0, [("culture_2", 0.9)], []),
  ("culture_3", "Apaches", 0, 0.0, [("culture_3", 0.9)], []),
  ("culture_4", "Comanches", 0, 0.0, [("culture_4", 0.9)], []),
  ("culture_5", "Gang_Mexico", 0, 0.0, [("culture_5", 0.9)], []),
  ("culture_6", "Gang_Lawmen", 0, 0.0, [("culture_6", 0.9)], []),
  ("culture_7", "Gang_Outlaws", 0, 0.0, [("culture_7", 0.9)], []),
  ("player_faction", "Player_Faction", 0, 0.0, [("commoners", 0.1),("outlaws", -0.05),("deserters", -0.02),("player_faction", 0.9),("player_supporters_faction", 1),("confederate_renegades", -0.01),("imperialists", -0.01),("scalphunters", -0.01),("indian_raiders", -0.15),("wild_animals", -0.15),("undeads", -0.5),("peasant_rebels", -0.4),("bounty_hunters", 1)], []),
  ("player_supporters_faction", "Player_Faction", 0, 0.0, [("outlaws", -0.05),("deserters", -0.02),("player_faction", 1),("player_supporters_faction", 0.9),("peasant_rebels", -0.1),("bounty_hunters", 1)], []),
  ("kingdom_1", "USA", 0, 0.0, [("outlaws", -0.05),("deserters", -0.02),("kingdom_1", 0.9),("confederate_renegades", -0.1),("scalphunters", -0.1),("indian_raiders", -0.1),("peasant_rebels", -0.1)], [], 0x4169E1),
  ("kingdom_2", "Mexico", 0, 0.0, [("outlaws", -0.05),("deserters", -0.02),("kingdom_2", 0.9),("confederate_renegades", 0.1),("imperialists", -0.1),("scalphunters", 0.1),("indian_raiders", -0.1),("peasant_rebels", -0.1)], [], 0x8000),
  ("kingdom_3", "Apaches", 0, 0.0, [("outlaws", -0.05),("deserters", -0.02),("kingdom_3", 0.9),("scalphunters", -0.1),("indian_raiders", 0.1),("peasant_rebels", -0.1)], [], 0x9E0508),
  ("kingdom_4", "Comanches", 0, 0.0, [("outlaws", -0.05),("deserters", -0.02),("kingdom_4", 0.9),("scalphunters", -0.1),("indian_raiders", 0.1),("peasant_rebels", -0.1)], [], 0xFFFF00),
  ("unused_1", "none_1", 0, 0.0, [("unused_1", 0.9)], []),
  ("unused_2", "none_2", 0, 0.0, [("unused_2", 0.9)], []),
  ("unused_3", "none_3", 0, 0.0, [("unused_3", 0.9)], []),
  ("unused_4", "none_4", 0, 0.0, [("unused_4", 0.9)], []),
  ("unused_5", "none_5", 0, 0.0, [("unused_5", 0.9)], []),
  ("unused_6", "none_6", 0, 0.0, [("unused_6", 0.9)], []),
  ("unused_7", "none_7", 0, 0.0, [("unused_7", 0.9)], []),
  ("unused_1b", "none_1b", 0, 0.0, [("unused_1b", 0.9)], []),
  ("unused_2b", "none_2b", 0, 0.0, [("unused_2b", 0.9)], []),
  ("unused_3b", "none_3b", 0, 0.0, [("unused_3b", 0.9)], []),
  ("unused_4b", "none_4b", 0, 0.0, [("unused_4b", 0.9)], []),
  ("unused_5b", "none_5b", 0, 0.0, [("unused_5b", 0.9)], []),
  ("unused_6b", "none_6b", 0, 0.0, [("unused_6b", 0.9)], []),
  ("unused_7b", "none_7b", 0, 0.0, [("unused_7b", 0.9)], []),
  ("unused_1c", "none_1c", 0, 0.0, [("unused_1c", 0.9)], []),
  ("unused_2c", "none_2c", 0, 0.0, [("unused_2c", 0.9)], []),
  ("unused_3c", "none_3c", 0, 0.0, [("unused_3c", 0.9)], []),
  ("unused_4c", "none_4c", 0, 0.0, [("unused_4c", 0.9)], []),
  ("unused_5c", "none_5c", 0, 0.0, [("unused_5c", 0.9)], []),
  ("unused_6c", "none_6c", 0, 0.0, [("unused_6c", 0.9)], []),
  ("unused_7c", "none_7c", 0, 0.0, [("unused_7c", 0.9)], []),
  ("kingdoms_end", "kingdoms_end", 0, 0.0, [], []),
  ("confederate_renegades", "Confederate_Renegades", 0, 0.0, [("deserters", -0.1),("player_faction", -0.01),("kingdom_1", -0.1),("kingdom_2", 0.1),("confederate_renegades", 0.5),("imperialists", 0.1),("scalphunters", -0.1),("indian_raiders", -0.1)], [], 0xFFAAFF),
  ("imperialists", "Imperialists", 0, 0.0, [("deserters", -0.1),("player_faction", -0.01),("kingdom_2", -0.1),("confederate_renegades", 0.1),("imperialists", 0.9),("scalphunters", 0.1),("indian_raiders", -0.1)], [], 0xFFAAFF),
  ("scalphunters", "Scalphunters", 0, 0.0, [("commoners", -0.5),("outlaws", -0.5),("deserters", -0.1),("player_faction", -0.01),("kingdom_1", -0.1),("kingdom_2", 0.1),("kingdom_3", -0.1),("kingdom_4", -0.1),("confederate_renegades", -0.1),("imperialists", 0.1),("scalphunters", 0.9),("indian_raiders", -0.1)], [], 0xFFAAFF),
  ("indian_raiders", "Indian_Raiders", 0, 0.0, [("commoners", -0.5),("outlaws", -0.5),("deserters", -0.1),("player_faction", -0.15),("kingdom_1", -0.1),("kingdom_2", -0.1),("kingdom_3", 0.1),("kingdom_4", 0.1),("confederate_renegades", -0.1),("imperialists", -0.1),("scalphunters", -0.1),("indian_raiders", 0.9)], [], 0xFFAAFF),
  ("minor_end", "minor_end", 0, 0.0, [], []),
  ("wild_animals", "Wild_Animals", 0, 0.0, [("player_faction", -0.15),("wild_animals", 0.1)], [], 0xFFFFFF),
  ("robber_knights", "robber_knights", 0, 0.0, [("robber_knights", 0.1)], []),
  ("undeads", "Undeads", max_player_rating(-30), 0.0, [("commoners", -0.7),("player_faction", -0.5),("undeads", 0.5)], []),
  ("peasant_rebels", "Peasant_Rebels", 0, 0.0, [("player_faction", -0.4),("player_supporters_faction", -0.1),("kingdom_1", -0.1),("kingdom_2", -0.1),("kingdom_3", -0.1),("kingdom_4", -0.1),("peasant_rebels", 1),("noble_refugees", -1),("bounty_hunters", 1)], []),
  ("noble_refugees", "Noble_Refugees", 0, 0.0, [("peasant_rebels", -1),("noble_refugees", 0.5)], []),
  ("bounty_hunters", "Bounty_Hunters", 0, 0.0, [("commoners", 1),("outlaws", 1),("deserters", 1),("player_faction", 1),("player_supporters_faction", 1),("peasant_rebels", 1),("bounty_hunters", 0.5)], []),
]